### ISSUE TITLE
Can get complete when typing 'this.' inside class functions

### ISSUE THREAD

**Issue by Misfit-John** [justmao945/vim-clang#100]
I can't get any complete when I type this. inside a cpp class, but if I specify some prefix, the list pop out. Also if I create a new object of that class, I can get list.

Can you tell me know to trobule shot on this issue ?  i remember clang-complete uses clang's complete option to make the list, how is your command? Maybe I can help if you can't reproduce it locally .

**Comment by Misfit-John** [comment]
My bad, writing too long for golang makes me forget that I should use this-> in c .

**Comment by justmao945** [comment]
😄 haha. I'm writing golang as well.
