### ISSUE TITLE
Don't autofill first entry when autocompleting with neocomplete

### ISSUE THREAD

**Issue by dutchgecko** [justmao945/vim-clang#104]
Hi,

I'm having some issues getting my configuration set up. At the moment it looks like this:

``` viml
"#############################################################################
"### Neocomplete settings                                           {{{1    ##
"#############################################################################
if has('lua')
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_smart_case = 1
    let g:neocomplete#sources#syntax#min_keyword_length = 3
endif

" C(++) input patterns for neocomplete to open omnicomplete from vim-clang
let g:neocomplete#force_omni_input_patterns.c =
    \ '[^.[:digit:] *\t]\%(\.\|->\)\w*'
let g:neocomplete#force_omni_input_patterns.cpp =
    \ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'

"#############################################################################
"### vim-clang settings                                             {{{1    ##
"#############################################################################
let g:clang_auto = 0    " disable own autocompletion as neocomplete takes over

" 'longest' option does not work with neocomplete
let g:clang_c_completeopt = 'menuone,preview'
let g:clang_cpp_completeopt = 'menuone,preview'

" Use 2011 standards by default
let g:clang_c_options = '-std=gnu11'
let g:clang_cpp_options = '-std=c++11'
```

When triggering the autocompletion, for example by typing `std::`, the first entry in the menu is automatically entered into the buffer (for example, `std::advance`). I would like for this not to occur.

I have tried the following additional settings, without success:

- `let g:lang_cpp_completeopt = 'longest'`
- `let g:neocomplete#enable_auto_select = 0`
- `let g:neocomplete#force_overwrite_completefunc = 1`

What am I doing wrong?

**Comment by Shougo** [comment]
```vim
let g:clang_c_completeopt = 'menuone,preview,noinsert'
let g:clang_cpp_completeopt = 'menuone,preview,noinsert'
```

**Comment by dutchgecko** [comment]
Thank you, that works.

Is that option documented anywhere? I couldn't find it in the help file.

**Comment by unphased** [comment]
The config doesn't work because it resolves the first item getting filled in (and subsequent typing not able to change it), but now the behavior becomes, the first result (which is almost always right) is never filled in, so i have to press Tab and Shift+Tab just to get it to fill the first result...

**Comment by Shougo** [comment]
@unphased You can press `<CR>` or `<C-y>` to insert the first candidate.
