### ISSUE TITLE
How to get to me autocomplit of include files?

### ISSUE THREAD

**Issue by fedor-elizarov** [justmao945/vim-clang#106]
for example
`#include <SDL2/SDL.h>

void main(void)
{
      SDL_ //and here I am waiting pop-up witch complete SDL_Init(Uint32)
                //but me need <c-x> <c-o> to get this (( 
                //and I want to be automatically 
}
`
P.S. sorry for my English

**Comment by fedor-elizarov** [comment]
and my vimrc  this https://gist.github.com/fedor-elizarov/c706f08c0597c8ca1fc6d6d4faeed532

**Comment by justmao945** [comment]
I can't understand for what you want to get.
get (( ?

**Comment by fedor-elizarov** [comment]
oh sorry, my english is very bad ((
I decided my problem -> vim-clang + neocomplete 
the question is closed, thanks ::)

**Comment by justmao945** [comment]
OK. 😄
