### ISSUE TITLE
How to reload `.clang`?

### ISSUE THREAD

**Issue by krsch** [justmao945/vim-clang#108]
Is it possible to reload `.clang`? I don't like restarting gvim after finding out that I have forgot one `-I` flag in `.clang`.

**Comment by justmao945** [comment]
Yes, you can run `: ClangCompleteInit`

https://github.com/justmao945/vim-clang/blob/master/plugin/clang.vim#L1057

**Comment by krsch** [comment]
Thanks, it works!
