### ISSUE TITLE
Menu not opening with gvim

### ISSUE THREAD

**Issue by markand** [justmao945/vim-clang#114]
Hello,

Thank you for this awesome plugin!

This plugin works pretty fine on my Fedora 27 if I use vim in terminal. However, in gvim, typing ^X^O to complete a symbol does not open any completion menu. I just see the prompt changing from completion mode and back to insert immediately.

    -- ^X mode (...)
    -- INSERT --

Do you know why it does not work with gvim?

**Comment by syswow** [comment]
Hi @markand ,

Thank you for taking the time to report this problem!

The diff posted below works as expected on my Fedora 27 VBox.

```patch
diff --git a/plugin/clang.vim b/plugin/clang.vim
index 35b7f3e..3ab3a08 100644
--- a/plugin/clang.vim
+++ b/plugin/clang.vim
@@ -115,6 +115,8 @@ endif
 if !exists('g:clang_vim_exec')
   if has('mac')
     let g:clang_vim_exec = 'mvim'
+  elseif has('gui_running')
+    let g:clang_vim_exec = 'gvim'
   else
     let g:clang_vim_exec = 'vim'
   endif
```

**Comment by justmao945** [comment]
So what's the real problem ? can't execute vim ?

**Comment by markand** [comment]
Thanks @syswow, it works well. @justmao945 would you mind committing this? As explained in my initial message. The plugin does not popup the menu when trying to complete in gvim.

**Comment by justmao945** [comment]
@syswow Can you make a pull request for your patch ?

**Comment by syswow** [comment]
@justmao945 OK
