### ISSUE TITLE
Use of compile_commands.json doesn't support python3

### ISSUE THREAD

**Issue by bergercookie** [justmao945/vim-clang#116]
The `python << endpython` expression [here](https://github.com/justmao945/vim-clang/blob/master/plugin/clang.vim#L900) doesn't support python3.

A potential way of generalizing to support either version, would be [this](https://vi.stackexchange.com/a/10926/6972)

Cheers,

**Comment by justmao945** [comment]
Do you mind to create a pull request for it? Thank you.

**Comment by justmao945** [comment]
#83

**Comment by bergercookie** [comment]
I can try.. :-)

I'll let you know if/when I have this ready! 

Cheers,
Nikos

**Comment by shuber2** [comment]
Pull request #123 solves this issue by selecting the python infrastructure as in deoplete.

**Comment by bergercookie** [comment]
:+1:
