### ISSUE TITLE
buffer/window name/type for autocomplete

### ISSUE THREAD

**Issue by mckellyln** [justmao945/vim-clang#117]
Hi,
Thx for vim-clang.
When I use autocomplete I get a new window at the top -
Q: does this buffer have a name/type I can use to help with its statusline editting ?
Q: Is there a way to close this automatically after the autocomplete is finished ?

**Comment by Shougo** [comment]
> Q: does this buffer have a name/type I can use to help with its statusline editting ?

https://github.com/Shougo/echodoc.vim

> Q: Is there a way to close this automatically after the autocomplete is finished ?

```vim
        autocmd CompleteDone * silent! pclose!
```

**Comment by mckellyln** [comment]
Thx so much,
```
autocmd CompleteDone * silent! pclose!
```
works great.
I will also look into the echodoc.vim plugin.
