### ISSUE TITLE
Not working with gVim 8.2.2529

### ISSUE THREAD

**Issue by Pinaki82** [justmao945/vim-clang#142]
This is one of the vital plugins I always install when I install Vim. It worked fine until I tried [gVim 8.2.2529](https://github.com/vim/vim-win32-installer/releases). Got the following error while trying to autocomplete a line of a C code. Please fix the issue since without this plugin I can't imagine working with Vim at all. Thanks in advance!

![2021-02-19 22_21_16-crsh c + (Q__codes_crashtst) - GVIM](https://user-images.githubusercontent.com/16861933/108536184-24d50080-7302-11eb-82f0-11562888a2d7.png)

The code is here:

```
// Last Change: 2016-04-19  Tuesday: 10:56:00 AM
#include <omp.h>
#include <errno.h>
#include <stdint.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  #pragma omp parallel
  {
    int *p;
    p = (int *)malloc((size_t)1 * sizeof(int));
    if(p==NULL) {
      printf("\ndynamic memory allocation failed\n");
      exit(EXIT_FAILURE);
    }
    *p=5;
    printf("%d\n", *p);
    free(p);
    p = NULL;
  }
  getchar();
  return 0;
}


```

**Comment by mckellygit** [comment]
Look at pull request https://github.com/justmao945/vim-clang/pull/140
It is my first attempt at fixing this issue.

**Comment by Pinaki82** [comment]
> Look at pull request #140
> It is my first attempt at fixing this issue.

Works like a charm, except for one problem:  First, a warning is displayed, then it starts working without producing any error message at all. It's probably due to an abrupt change pushed by the Vim devs that introduced the bug. Could we report the same to their (I mean, [Vim Win32](https://github.com/vim/vim-win32-installer.git)]) repo instead of trying hard to fix it here? Just asking!  @justmao945 should merge the commit as a temporary measure. Thanks!

![2021-02-20 00_31_22-crsh c + (Q__codes_crashtst) - GVIM](https://user-images.githubusercontent.com/16861933/108550215-42ab6100-7314-11eb-934c-38b1ea3dce6e.png)

**Comment by mckellygit** [comment]
ok, maybe I can fix those.  Let me look.

**Comment by Pinaki82** [comment]
> ok, maybe I can fix those. Let me look.

So many thanks for your assurance! I hope that the problem will be fixed soon with your ardent efforts. Meanwhile, could we not report the issue to the Vim developers? If it is a bug in the latest version of Vim, it should be fixed internally. If window resizing is withdrawn from the latest version of Vim, it's abrupt as it would break so many plugins, hence must not be incorporated into the next stable release. Vim is bread and butter for many people. This type of decisions must not disrupt end-users. Please report the issue there so they feel that it's not justified to stand in the way of someone's workflow. Please, also report the issue there!

**Comment by mckellygit** [comment]
I pushed an update to my PR.  See if that fixes the errors you see at start.
I did bring this up in the vim dev group.  They just said that changing windows from a complete func is not allowed anymore.
So I decided to change the plugin to not do that.  I am not a vim script expert by any means so I am sure there is a better way than this, but its my quick attempt at resolving it.
I will work on it and improve it and perhaps it or something else better will get merged soon.
PS I think nvim is fine with the original plugin as is.

**Comment by Pinaki82** [comment]
> I pushed an update to my PR. See if that fixes the errors you see at start.
> I did bring this up in the vim dev group. They just said that changing windows from a complete func is not allowed anymore.
> So I decided to change the plugin to not do that. I am not a vim script expert by any means so I am sure there is a better way than this, but its my quick attempt at resolving it.
> I will work on it and improve it and perhaps it or something else better will get merged soon.
> PS I think nvim is fine with the original plugin as is.

Amazing!! Didn't expect that the fix would come so early! I cloned it from your personal repo  https://github.com/mckellygit/vim-clang.git using vim-plug. Everything worked as if I was running a sharp knife through butter. Let the issue not closed until @justmao945 merges it to the master branch. Yes, NVim will work fine. But I'm not sure why Vim developers decided to take a strong stance on disallowing window resizing from a function. What's the point I'm not sure! Zuckerberg's theory of moving fast to unnecessarily break things shouldn't be applied to Vim philosophy. I'm quite disappointed with this decision. You fixed it with so hard efforts! All the credits go to you only. Thanks again!

**Comment by mckellygit** [comment]
Just an fyi - I pushed one minor update - should be the same just cleaner code.

**Comment by Pinaki82** [comment]
> Just an fyi - I pushed one minor update - should be the same just cleaner code.

Worked perfectly as expected. A new problem cropped up while updating the plugin which I solved by deleting the plugin folder from the 'vim-plug' directory 'plugged/vim-clang'. Much cleaner and understandable code that works without any flaw. Create a pull request with the latest changes. Let not the issue closed until your latest commit gets merged. So many thanks!

![2021-02-20 11_38_23- Plugins  - (C__Users_AppuRaja_PortableApps_gVimPortable) - GVIM](https://user-images.githubusercontent.com/16861933/108586079-2c33f280-7372-11eb-903a-d2613ac91b16.png)

**Comment by Pinaki82** [comment]
Hello, @mckellygit and @justmao945! The issue has been fixed. @mckellygit's pull request has been merged with the master branch by @justmao945. I tested it and it's working without any hiccup as far as I experienced. The problem is no longer present in the latest version, to my best knowledge. Many thanks go to both of you! Now anyone of you should proceed to close the issue. Thanks again!!

**Comment by justmao945** [comment]
OK, thank you for your testing. 💯

**Comment by Pinaki82** [comment]
> OK, thank you for your testing. 💯

You're most welcome!
