### ISSUE TITLE
Support for JSON Compilation Database

### ISSUE THREAD

**Issue by jonthn** [justmao945/vim-clang#26]
Hello,

I don't know if your plugin support this feature but that would be a great addition if that's not the case.
see http://clang.llvm.org/docs/JSONCompilationDatabase.html

Basically you store all the flags required to compile a C/C++ source file in a file 'compile_commands.json' so it's not needed anymore to explicitly add each flags and includes.

**Comment by justmao945** [comment]
Unsupported yet, I can't find the clang option to load this file 'compile_commands.json' in Clang 3.5.
It's a feature in clang tool and libclang, so it seems not easy to implement this only use the clang executable.

**Comment by justmao945** [comment]
@jonthn 
Hi, this feature was added by @c0r73x , so you can update to the latest version if you want to have a try.

**Comment by jonthn** [comment]
@justmao945 thanks for the "heads up", I'll give it a try soon.
