### ISSUE TITLE
OmniCompletion selection is broken

### ISSUE THREAD

**Issue by Werror** [justmao945/vim-clang#27]
Hi I am new to your script and love using it and it works fine until a few days ago I updated.
Basically when I type :: I do get the completion popup however when I want to select using up/down, the vim functionality is broken and I have no way of saving and continue the work.

Would you help me look at this problem?

**Comment by justmao945** [comment]
I fix a problem about 2 days ago, and it works well on my machine.
Please update your script to the master HEAD. Type std:: and select by Ctrl P/N or Up/Down arrow key are fine.

Or can you provide more info about the broken?

**Comment by Werror** [comment]
Hey Thank you for your information, I think after update it worked fine now :) again thanks a lot

**Comment by justmao945** [comment]
You are welcome :smile:
