### ISSUE TITLE
Annoying message complaint when changing buffer

### ISSUE THREAD

**Issue by sim590** [justmao945/vim-clang#28]
When the plugin is active (even if diagnostics are disabled using `let g:clang_diagsopt = ''`) and I try to change buffer using `:buffer <number>`, I get this message : 
```
Error detected while processing function <SNR>110_DiagnosticsPreviewWindowClose..<SNR>110_DiagnosticsWindowC
lose:
line   15:
E121: Undefined variable: t:clang_diags_driver_bufnr
```

Since the variable may not have been set, I guess that a quick fix would be to change this [line](https://github.com/justmao945/vim-clang/blob/master/plugin/clang.vim#L398) to : 
```vim
  if !exists('t:clang_diags_bufnr') || !exists('t:clang_diags_driver_bufnr')
```

**Comment by justmao945** [comment]
Yes, that's my mistake on branch master, I fixed this yesterday. Please pull the master.

**Comment by sim590** [comment]
One of the tab variable is checked, but not the other on 6da93f9 (https://github.com/justmao945/vim-clang/blob/master/plugin/clang.vim#L398). I think both of those variables have to be checked : 
```vim
t:clang_diags_bufnr
t:clang_diags_driver_bufnr
```

**Comment by justmao945** [comment]
OK, I'll add it
