### ISSUE TITLE
add 'Command' to show autocomplete list

### ISSUE THREAD

**Issue by syswow** [justmao945/vim-clang#30]
so we can map this command to 'space+ctrl'.

**Comment by justmao945** [comment]
Do you mean Ctrl+x then Ctrl+o ?  You can map `<C-X><C-O>` to `space+ctrl`.

e.g.
```
# include <stdio.h>
int main() {
   pri
      ^  now press ctrl+x and ctrl+o, which will trigger the autocompletion.

}
```

For more details to see `:h i_CTRL_X-CTRL_O`.

**Comment by syswow** [comment]
Thanks
