### ISSUE TITLE
press 'key' to force show diagnostics window ?

### ISSUE THREAD

**Issue by syswow** [justmao945/vim-clang#34]

**Comment by justmao945** [comment]
Eh, this should be a nice feature and it not difficult to do in current version, I'll do it when I have time.
Something I think can do:
1. add command(able to map to key) to run clang syntax check and show diagnostics window.
2. auto run syntax when user save file.

If you have time and are interesting in implementing this feature, you can have a try. :smile:

**Comment by syswow** [comment]
@justmao945 
Hi, I have try to implement this feature, it works both for vim and neovim

>  1. add command(able to map to key) to run clang syntax check and show diagnostics window.
>  2. auto run syntax when user save file.

see https://github.com/syswow/nvim-clang/tree/add-diagnostics-windows-command

but it base on #35 

Any advice is welcome. :smile:

**Comment by justmao945** [comment]
Thank you @syswow . Very great work. Please send me pull request, then I'll review and merge it.

**Comment by syswow** [comment]
Wait, I find some bugs.... Need more work....

**Comment by justmao945** [comment]
It's OK. :smile:

**Comment by syswow** [comment]
@justmao945  I thank before continue to implement this feature, we have to fix #41.  How do you see it?

**Comment by justmao945** [comment]
Dose something i #41 blocks this feature ?

**Comment by syswow** [comment]
yes, when the diag window show, we cannot change buffer.

**Comment by justmao945** [comment]
I don't understand why need to change buffer ?

**Comment by syswow** [comment]
":e somefile" is basic operation.

**Comment by justmao945** [comment]
I know the problem, but what I want to say is that in fact you can implement this feature for saving file, e.g. `:w`.

**Comment by justmao945** [comment]
New command `ClangSyntaxCheck` is added
