### ISSUE TITLE
vim-clang doest work, when i run 'vim test_new.cpp', to create a new cpp file.

### ISSUE THREAD

**Issue by syswow** [justmao945/vim-clang#36]

**Comment by justmao945** [comment]
Yeah, I also found this problem.

**Comment by justmao945** [comment]
Here's the problem, need to find a good solution, https://github.com/justmao945/vim-clang/commit/7150159ebff18c06ff6c8bc2f27323c966b5b71a

**Comment by justmao945** [comment]
I think I fix this problem, please verify it. @syswow

**Comment by syswow** [comment]
confirm fixed on Ubuntu. @justmao945
