### ISSUE TITLE
[BUG]  run ":e somefile" will quit vim

### ISSUE THREAD

**Issue by syswow** [justmao945/vim-clang#41]
Reproduce:
1. open file
2. wirte some syntax error lines, then do complete
3. show diag window
4. run ":e somefile"

**Comment by syswow** [comment]
@justmao945 Need fix

**Comment by justmao945** [comment]
I know. but need time to do this. can you have a try? seems have problem when close diagnostic window

**Comment by justmao945** [comment]
This bug is not easy to fix...I don't know `BufWinLeave` is triggered by `:q`, `:e` or any other commands...And I don't know if there's a good way to close diag window when its driver source buffer is unloaded..

Another question, seems 
```viml
try
  hide
catch
endtry
```
doesn't work in function diags window open.

**Comment by justmao945** [comment]
I'll disable the feature that close diag window when the source is unloaded automatically until we fix this issue.

**Comment by justmao945** [comment]
Fixed in latest commit.
