### ISSUE TITLE
[BUG]  Keeping Press 'TAB' scroll through complete-list will flash screen

### ISSUE THREAD

**Issue by syswow** [justmao945/vim-clang#42]
Reproduce:
1.  Install:
```viml
Plug 'ervandew/supertab'
let g:SuperTabDefaultCompletionType = "<c-x><c-o>"
let g:SuperTabRetainCompletionDuration = 'insert'
```

2 .   Write down short cpp
```cpp
#include <iostream>
int main()
{
    std::
}
```

3  . Keeping press 'TAB; scroll throgh list, will flash screen.

**Comment by justmao945** [comment]
On my machine, screen flashes slightly... I don't know how to fix it, is this related to supertab ? I think this is caused by the GUI of GVIM, but I'm not sure if we can fix it or not.

**Comment by syswow** [comment]
@justmao945  also, I find if the code is full window, then the screen flash just disapper...
