### ISSUE TITLE
Fails when used with vim-fugitive for :Gdiff command

### ISSUE THREAD

**Issue by albertnetymk** [justmao945/vim-clang#50]
Inside a git repo, starting with a file using vim, then `:Gd`, which should open two-column diff, but, instead, it fails with this msg:

```
Error detected while processing function <SNR>50_ClangCompleteInit:
line    8:
E472: Command failed
```
I am using commit 0e47495aa . I thought #20 has taken care of that.

**Comment by justmao945** [comment]
OK, I made a dirty patch to disable vim-clang under `fugitive:///`.
You can try the latest version.
#20 also has problem, that prevents loading of vim-clang when creating new file.
e.g.
```c++
# new.cc is not on disk yet
vim new.cc
```

**Comment by albertnetymk** [comment]
Thank you for the quick reply. With more testing, it lacks one essential feature in #3, so I can not use it until that features is arrived.

**Comment by justmao945** [comment]
Ah, this is a really nice feature, but I think it's hard to add, and is not in my plan.
