### ISSUE TITLE
missing function prototype preview

### ISSUE THREAD

**Issue by jralphur** [justmao945/vim-clang#57]
call pathogen#infect()                      " use pathogen
set backspace=indent,eol,start
let delimitMate_expand_cr=1
let g:clang_auto = 1
let g:clang_vim_exec = 'nvim'
let g:clang_cpp_options = '-std=c++11 -stdlib=libc++'
let g:clang_cpp_completeopt = 'longest,menuone,preview'
colorscheme molokai
" AUTOCOMPLETION
filetype plugin on
set cot+=menuone " Show preview of function prototype
syntax enable
set formatoptions+=r
set formatoptions+=o
set formatoptions+=c
" Tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
filetype indent on
" set smartindent
set autoindent

" UI
set number
set cursorline
set wildmenu
" set lazyredraw
set showmatch
set showmode
set nowrap
set hlsearch
set incsearch
set ignorecase

set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup

map <F9> :!clang++ -std=c++11 -stdlib=libc++ -lc++abi -Wall % && ./a.out
map <F8> :w %

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

i don't seem to have the function prototype window anymore, is there something that i'm missing?

**Comment by justmao945** [comment]
`let g:clang_cpp_completeopt = 'longest,menuone,preview'` makes prototype in the preview window, not the popup menu. Do you have a preview window on the top of VIM window ?

**Comment by jralphur** [comment]
no preview menu showing up at all.

**Comment by jralphur** [comment]
Seem I got prototypes showing up now by scrolling through the available completions.
