### ISSUE TITLE
can't find include files

### ISSUE THREAD

**Issue by mcchichen** [justmao945/vim-clang#59]
it keeps saying fatal error, header file not found everytime I tried to do an autocompletion. however I have include the path in the .clang file(I tried both absolute path and relative path), and  I printed out the clang command used for completion and all the paths are included with -I option. The headers and sources are in subfolders of include/ and src/ . Any suggestions on how to make this work? thanks

**Comment by justmao945** [comment]
1. Add `let g:clang_debug = 2` to .vimrc 
2. start vim
3. type `:messages`
4. take a snapshot
5. you can type `tree` in your source directory and paste to comment.
