### ISSUE TITLE
Undefined variable: g:clang_diagsopt

### ISSUE THREAD

**Issue by codeinabox** [justmao945/vim-clang#63]
I just updated my plug-ins and I am getting this error on start up

> Error detected while processing /Users/matt/dotfiles/.vim/bundle/vim-clang/plugin/clang.vim:
line   38:
E121: Undefined variable: g:clang_diagsopt
E15: Invalid expression: g:clang_diagsopt !~# '^[a-z]\+\(:[0-9]\)\?$'

**Comment by justmao945** [comment]
Please confirm it, thank you~ :smile:

**Comment by codeinabox** [comment]
:+1 Error is gone after an update

**Comment by justmao945** [comment]
OK, thank you.
