### ISSUE TITLE
Set complete preview buffer position

### ISSUE THREAD

**Issue by DaSea** [justmao945/vim-clang#73]
How to set preview  buffer position to below?

**Comment by justmao945** [comment]
I don't know how to set the position preview buffer, which is provided by Vim. Seems can only be opened above current window.

**Comment by Shougo** [comment]
@DaSea You can use `splitbelow` option for it.
The default position is above.
It is Vim's feature.

```vim
:set splitbelow
```

**Comment by DaSea** [comment]
Thanks @Shougo , this is a global setting, and  i set it ,and open preview buffer in below!
