### ISSUE TITLE
neomake?

### ISSUE THREAD

**Issue by c0r73x** [justmao945/vim-clang#75]
The last commit breaks vim-clang for me.

Vim(let):E117: Unknown function: neomake#makers#ft#cpp#clang

From what I understand this is some sort of neovim function? Did you drop vim support?

**Comment by justmao945** [comment]
Sorry for that.
@minijackson can you give a fix ?

**Comment by minijackson** [comment]
I'm on it.

**Comment by minijackson** [comment]
@c0r73x This function is from the Neomake plugin (https://github.com/benekastah/neomake) which is basically an asynchronous Syntastic for neovim. I just forgot to check if the function existed before using it, my bad.

**Comment by c0r73x** [comment]
No problem, it just surprised me :p
