### ISSUE TITLE
vim-clang not work with split window

### ISSUE THREAD

**Issue by jsfaint** [justmao945/vim-clang#97]
When edit code with split window(same file), press `<c-x><c-o>` or press `.` to complete member in struct.
vim-clang will change the cursor window
![vim-clang1](https://cloud.githubusercontent.com/assets/571829/17733268/6067a142-64a8-11e6-9df2-49aac8d1e62d.gif)

And this message will show in `:message`
![change](https://cloud.githubusercontent.com/assets/571829/17733213/18d944b6-64a8-11e6-9ccc-0f53df5387c4.png)

Edit in the left window is ok, this issue only happy in the right window.
For vertical split view, this issue happens in the bottom window.

I also reproduce this issue in linux and osx.

Thanks

**Comment by justmao945** [comment]
It's buggy when split with the **same** buffer...Seems a bug of VIM.

**Comment by jsfaint** [comment]
But for other plugin like jedi-vim/neocomplete, I can't reproduce this issue. 😢

**Comment by jsfaint** [comment]
This issue was fixed in recently vim. close it 😄 
Thanks for reply
